version: "3"
services:
  factorio-server-manager:
    image: "ofsm/ofsm:latest"
    container_name: "factorio-server-manager"
    restart: "unless-stopped"
    environment:
      - "FACTORIO_VERSION=stable"
      - "RCON_PASS"
    ports:
      - "80:80"
      - "34197:34197/udp"
    volumes:
      - "./fsm-data:/opt/fsm-data"
      # Managed servers, saves, mods, and downloaded versions live here.
      - "./factorio-server:/opt/factorio-server"
