FROM alpine:latest AS build
RUN apk add --no-cache git make musl-dev go nodejs npm zip mingw-w64-gcc
ENV GOROOT=/usr/lib/go
ENV GOPATH=/go
ENV PATH=/go/bin:$PATH
ENV FACTORIO_ROOT=/go/src/factorio-server-manager

RUN mkdir -p ${GOPATH}/bin
WORKDIR $FACTORIO_ROOT

# Кешируем Go зависимости отдельно
COPY src/go.mod src/go.sum ./src/
RUN cd src && go mod download

# Кешируем npm зависимости отдельно
COPY package.json package-lock.json ./
RUN npm install

# Копируем остальное
COPY ./ ./

COPY docker/build-release.sh /usr/local/bin/build-release.sh
RUN sed -i 's/\r$//' /usr/local/bin/build-release.sh && chmod u+x /usr/local/bin/build-release.sh

VOLUME /build
VOLUME $FACTORIO_ROOT
RUN sh /usr/local/bin/build-release.sh

FROM scratch AS output
COPY --from=build /go/src/factorio-server-manager/build/* .
